import SwiftUI
import SwiftData

/// Desktop "Today": shows today's plan timeline (the woven anchors + routines +
/// goal-work) and can generate one through the SAME generation path the iOS app
/// uses — AIService (BYOK) when an API key is configured, otherwise the offline
/// PlanGenerator + DailyTimeline template. Actions can be marked done or skipped,
/// writing straight back to the same SwiftData store that iOS reads over CloudKit.
struct MacTodayView: View {
    @Environment(ThemeManager.self) private var tm
    @Environment(\.modelContext) private var context

    @Query(filter: #Predicate<Goal> { $0.isActive }) private var goals: [Goal]
    @Query(sort: \DailyPlan.date, order: .reverse) private var plans: [DailyPlan]
    @Query(sort: \UserPreferences.id) private var preferences: [UserPreferences]
    @Query private var profiles: [UserProfile]
    @Query(sort: \IntegrationSnapshot.date, order: .reverse) private var snapshots: [IntegrationSnapshot]
    @Query(sort: \Reflection.date, order: .reverse) private var reflections: [Reflection]

    @State private var isGenerating = false

    private var profile: UserProfile? { profiles.first }
    private var latestSnapshot: IntegrationSnapshot? { snapshots.first }
    private var prefs: UserPreferences? { preferences.first ?? profile?.userPreferences }

    private var todayPlan: DailyPlan? {
        plans.first { Calendar.current.isDateInToday($0.date) }
    }

    private var actions: [PlannedAction] {
        (todayPlan?.actions ?? []).sorted { $0.timeSlot < $1.timeSlot }
    }

    private var maxActions: Int {
        profile?.workStylePreference?.maxActionsPerDay ?? 6
    }

    var body: some View {
        let theme = tm.resolved
        MacScreen("Today", subtitle: Date.now.formatted(date: .complete, time: .omitted)) {
            HStack(spacing: 10) {
                if isGenerating { ProgressView().controlSize(.small) }
                Button {
                    generatePlan()
                } label: {
                    Label(todayPlan == nil ? "Generate Today's Plan" : "Regenerate Plan",
                          systemImage: "wand.and.stars")
                }
                .buttonStyle(.borderedProminent)
                .disabled(isGenerating || goals.isEmpty)
            }
        } content: {
            if AIConfig.isConfigured {
                Text("Plans are generated by your AI mentor (BYOK key in Settings).")
                    .font(theme.body(12))
                    .foregroundStyle(theme.faint)
            } else {
                Text("No API key set — plans are built offline from your goals. Add a key in Settings for AI-woven plans.")
                    .font(theme.body(12))
                    .foregroundStyle(theme.faint)
            }

            if goals.isEmpty {
                MacCard {
                    Text("Add a goal first — your plan is built from your active goals.")
                        .font(theme.body(14))
                        .foregroundStyle(theme.muted)
                }
            } else if actions.isEmpty {
                MacCard {
                    Text(todayPlan == nil
                         ? "No plan for today yet. Generate one to weave your goals into a timeline."
                         : "This plan has no actions.")
                        .font(theme.body(14))
                        .foregroundStyle(theme.muted)
                }
            } else {
                if let plan = todayPlan {
                    let done = (plan.actions ?? []).filter { $0.statusRaw == "done" }.count
                    MacCard("Timeline") {
                        Text("\(done) of \(actions.count) done")
                            .font(.system(size: 11, weight: .semibold, design: .monospaced))
                            .foregroundStyle(theme.muted)
                        ForEach(actions) { action in
                            actionRow(action)
                            if action.id != actions.last?.id {
                                Divider().overlay(theme.hair)
                            }
                        }
                    }
                }
            }
        }
    }

    @ViewBuilder
    private func actionRow(_ action: PlannedAction) -> some View {
        let theme = tm.resolved
        let done = action.statusRaw == "done"
        let skipped = action.statusRaw == "skipped"
        HStack(alignment: .top, spacing: 12) {
            Button {
                toggleDone(action)
            } label: {
                Image(systemName: done ? "checkmark.circle.fill" : "circle")
                    .font(.system(size: 18))
                    .foregroundStyle(done ? theme.ok : theme.muted)
            }
            .buttonStyle(.plain)

            VStack(alignment: .leading, spacing: 3) {
                HStack(spacing: 6) {
                    anchorBadge(action.anchorKind, theme: theme)
                    Text(action.title)
                        .font(theme.body(15))
                        .foregroundStyle(skipped ? theme.faint : theme.ink)
                        .strikethrough(done || skipped, color: theme.muted)
                }
                HStack(spacing: 8) {
                    Text(action.scheduleCue.isEmpty ? action.timeSlot : action.scheduleCue)
                    Text("·")
                    Text("\(action.durationMinutes) min")
                    if let g = action.goalTitleSnapshot, !g.isEmpty {
                        Text("·")
                        Text(g)
                    }
                }
                .font(.system(size: 11, design: .monospaced))
                .foregroundStyle(theme.muted)
            }
            Spacer()

            Button {
                toggleSkip(action)
            } label: {
                Text(skipped ? "Skipped" : "Skip")
                    .font(.system(size: 11, weight: .semibold, design: .monospaced))
                    .foregroundStyle(skipped ? theme.deferred : theme.muted)
            }
            .buttonStyle(.plain)
        }
        .padding(.vertical, 4)
    }

    @ViewBuilder
    private func anchorBadge(_ kind: PlannedAction.AnchorKind, theme: ResolvedTheme) -> some View {
        let (label, color): (String, Color) = {
            switch kind {
            case .fixed: return ("FIXED", theme.muted)
            case .routine: return ("ROUTINE", theme.accent)
            case .goalWork: return ("GOAL", theme.ok)
            }
        }()
        Text(label)
            .font(.system(size: 8, weight: .bold, design: .monospaced))
            .foregroundStyle(color)
            .padding(.horizontal, 5)
            .padding(.vertical, 2)
            .background(RoundedRectangle(cornerRadius: 4).fill(color.opacity(0.12)))
    }

    private func toggleDone(_ action: PlannedAction) {
        if action.statusRaw == "done" {
            action.statusRaw = "pending"
            action.completedAt = nil
        } else {
            action.statusRaw = "done"
            action.completedAt = .now
            action.skipReason = nil
        }
        try? context.save()
    }

    private func toggleSkip(_ action: PlannedAction) {
        if action.statusRaw == "skipped" {
            action.statusRaw = "pending"
        } else {
            action.statusRaw = "skipped"
            action.completedAt = nil
        }
        try? context.save()
    }

    // MARK: - Generation (same path as iOS)

    private func generatePlan() {
        guard !goals.isEmpty, !isGenerating else { return }
        isGenerating = true
        Task {
            defer { isGenerating = false }

            // Remove any existing plan for today so we don't stack duplicates.
            if let existing = todayPlan {
                context.delete(existing)
            }

            let plan = DailyPlan(date: .now, format: .focusBlocks)
            context.insert(plan)

            let built: [PlannedAction]
            if AIConfig.isConfigured, let aiActions = await buildAIActions() {
                built = aiActions
            } else {
                built = buildTemplateActions()
            }
            for action in built {
                context.insert(action)
                action.plan = plan
            }
            plan.actionCount = (plan.actions ?? []).count
            try? context.save()
        }
    }

    /// Offline plan via the shared `PlanGenerator` — the same timeline engine the
    /// iOS template (non-AI) fallback path uses.
    private func buildTemplateActions() -> [PlannedAction] {
        let timeline = PlanGenerator.generateTimeline(
            for: goals,
            prefs: prefs,
            freeMinutes: nil,
            maxGoalActions: maxActions
        )
        return timeline.map { entry in
            PlannedAction(
                title: entry.title,
                why: entry.why,
                timeSlot: entry.timeSlot,
                duration: entry.durationMinutes,
                goalID: entry.goalID,
                goalTitleSnapshot: entry.goalTitle,
                cueTrigger: entry.cueTrigger,
                targetAmount: entry.targetAmount,
                targetUnit: entry.targetUnit,
                anchorType: entry.anchorType.rawValue,
                scheduleCue: entry.scheduleCue
            )
        }
    }

    /// Calls the AI planner (`AIService.generatePlanJSON`) and parses its JSON into
    /// actions — the SAME generation path iOS uses. Returns nil on any failure so
    /// the caller falls back to templates.
    private func buildAIActions() async -> [PlannedAction]? {
        let planContext = AIService.PlanContext(
            recentDone: [],
            recentSkipped: [],
            latestReflection: reflections.first,
            userPreferences: prefs
        )
        do {
            let jsonText = try await AIService.generatePlanJSON(
                goals: goals,
                snapshot: latestSnapshot,
                profile: profile,
                planContext: planContext
            )
            guard let data = jsonText.data(using: .utf8),
                  let rows = try? JSONSerialization.jsonObject(with: data) as? [[String: Any]] else { return nil }
            let goalIDs = Set(goals.map { $0.id })
            var built: [PlannedAction] = []
            var goalWorkCount = 0
            for dict in rows {
                let anchorTypeRaw = dict["anchor_type"] as? String ?? "goal_work"
                let anchorKind = PlannedAction.AnchorKind(rawValue: anchorTypeRaw) ?? .goalWork
                if anchorKind == .goalWork {
                    if goalWorkCount >= maxActions { continue }
                    goalWorkCount += 1
                }
                var resolvedGoalID: UUID? = nil
                if let s = dict["goal_id"] as? String, let parsed = UUID(uuidString: s), goalIDs.contains(parsed) {
                    resolvedGoalID = parsed
                }
                let resolvedGoal = resolvedGoalID.flatMap { gid in goals.first { $0.id == gid } }

                var targetAmount: Double? = nil
                if let v = dict["target_amount"] as? Double { targetAmount = v }
                else if let v = dict["target_amount"] as? Int { targetAmount = Double(v) }

                built.append(PlannedAction(
                    title: dict["title"] as? String ?? "",
                    why: dict["why"] as? String ?? "",
                    timeSlot: dict["time_slot"] as? String ?? "",
                    duration: dict["duration_minutes"] as? Int ?? 30,
                    goalID: anchorKind == .goalWork ? resolvedGoalID : nil,
                    goalTitleSnapshot: anchorKind == .goalWork ? resolvedGoal?.title : nil,
                    cueTrigger: dict["cue_trigger"] as? String ?? "",
                    targetAmount: targetAmount,
                    targetUnit: dict["target_unit"] as? String ?? "",
                    anchorType: anchorKind.rawValue,
                    scheduleCue: dict["schedule_cue"] as? String ?? ""
                ))
            }
            // If the AI left slots blank, assign from fixed defaults.
            if built.contains(where: { $0.timeSlot.isEmpty }) {
                let durations = built.map { $0.durationMinutes }
                let slots = SlotScheduler.assignSlots(count: built.count, durations: durations, freeMinutes: nil)
                for (i, action) in built.enumerated() where action.timeSlot.isEmpty {
                    action.timeSlot = i < slots.count ? slots[i] : ""
                }
            }
            return built.isEmpty ? nil : built
        } catch { return nil }
    }
}
